# Turkish translations for PACKAGE package.
# Copyright (C) 2020 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# audi06_19 <info@dreamosat-forum.com>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: enigma2-vision-core\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-03-21 01:17+0300\n"
"PO-Revision-Date: 2020-03-21 01:30+0300\n"
"Last-Translator: audi06_19 <info@dreamosat-forum.com>\n"
"Language-Team: Turkish\n"
"Language: tr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Poedit 2.2.1\n"
"X-Poedit-SourceCharset: UTF-8\n"

#: BackupManager.py:49 ImageManager.py:52
msgid "30 Days"
msgstr "30 Gün"

#: BackupManager.py:49 ImageManager.py:52
msgid "Daily"
msgstr "Günlük"

#: BackupManager.py:49 ImageManager.py:52
msgid "Weekly"
msgstr "Haftalık"

#: BackupManager.py:131 BackupManager.py:197 BackupManager.py:329
#: BackupManager.py:344 BackupManager.py:387 BackupManager.py:405
#: BackupManager.py:1147 ImageManager.py:372 ui.py:67
msgid "Backup manager"
msgstr "Yedekleme yöneticisi"

#: BackupManager.py:155
msgid "Restore"
msgstr "Geri yükle"

#: BackupManager.py:156 ImageManager.py:137 SwapManager.py:202
msgid "Delete"
msgstr "Sil"

#: BackupManager.py:171 BackupManager.py:305 ImageManager.py:157
#: ImageManager.py:313
msgid "%a %e %b  %-H:%M"
msgstr "%a %e %b  %-H:%M"

#: BackupManager.py:171 BackupManager.py:173 BackupManager.py:305
#: BackupManager.py:307 ImageManager.py:157 ImageManager.py:159
#: ImageManager.py:313 ImageManager.py:315
msgid "Next backup: "
msgstr "Sonraki yedekleme: "

#: BackupManager.py:200 BackupManager.py:341 BackupManager.py:384
#: ImageManager.py:186 ImageManager.py:359
msgid "View progress"
msgstr "İlerlemeyi görüntüle"

#: BackupManager.py:202 ImageManager.py:188
msgid "New backup"
msgstr "Yeni yedekleme"

#: BackupManager.py:229
msgid "Device: none available"
msgstr "Cihaz: mevcut değil"

#: BackupManager.py:229 ImageManager.py:238
msgid "Press 'Menu' to select a storage device"
msgstr "Bir depolama cihazı seçmek için 'Menü'ye basın"

#: BackupManager.py:245 BackupManager.py:248
msgid "Select a backup to restore:"
msgstr "Geri yüklenecek bir yedek seçin:"

#: BackupManager.py:245 ImageManager.py:257
msgid "The chosen location does not exist, using /media/hdd."
msgstr "/media/hdd kullanılarak seçilen konum mevcut değil."

#: BackupManager.py:248 BackupManager.py:268 ImageManager.py:262
#: ImageManager.py:271 MountManager.py:144 MountManager.py:279
#: MountManager.py:294
msgid "Device: "
msgstr "Cihaz: "

#: BackupManager.py:268 ImageManager.py:271
msgid "There is a problem with this device. Please reformat it and try again."
msgstr "Bu cihazla ilgili bir sorun var. Lütfen yeniden biçimlendirin ve tekrar deneyin."

#: BackupManager.py:313
msgid ""
"Are you sure you want to delete this backup:\n"
" "
msgstr ""
"Bu yedeklemeyi silmek istediğinizden emin misiniz:\n"
" "

#: BackupManager.py:315 ImageManager.py:323 Multibootmgr.py:138
#: Multibootmgr.py:142 Multibootmgr.py:157
msgid "Remove confirmation"
msgstr "Onayı kaldır"

#: BackupManager.py:317
msgid "There is no backup to delete."
msgstr "Silinecek yedek yok."

#: BackupManager.py:358
msgid "There is no backup to restore."
msgstr "Geri yüklenecek yedek yok."

#: BackupManager.py:360
msgid ""
"Backup in progress,\n"
"Please wait for it to finish, before trying again."
msgstr ""
"Yedekleme devam ediyor,\n"
"Lütfen tekrar denemeden önce bitmesini bekleyin."

#: BackupManager.py:371 BackupManager.py:373 RestoreWizard.py:185
#: RestoreWizard.py:189
msgid "Sorry, but the file is not compatible with this image version."
msgstr "Maalesef dosya bu resim sürümüyle uyumlu değil."

#: BackupManager.py:376
msgid ""
"Are you sure you want to restore this backup:\n"
" "
msgstr ""
"Bu yedeklemeyi geri yüklemek istediğinizden emin misiniz:\n"
" "

#: BackupManager.py:378
msgid "Restore Confirmation"
msgstr "Onayı Geri Yükle"

#: BackupManager.py:407 BackupManager.py:411 BackupManager.py:415
msgid "Restoring backup..."
msgstr "Yedekleme geri yükleniyor ..."

#: BackupManager.py:419 BackupManager.py:423 BackupManager.py:1157
#: BackupManager.py:1161
msgid "Creating list of installed plugins..."
msgstr "Yüklü eklentiler listesi yaratılıyor ..."

#: BackupManager.py:427 BackupManager.py:431
msgid "Comparing against backup..."
msgstr "Yedekle karşılaştırılıyor ..."

#: BackupManager.py:435 BackupManager.py:439
msgid "Restoring plugins..."
msgstr "Eklentiler geri yükleniyor ..."

#: BackupManager.py:443 BackupManager.py:447
msgid "Restoring plugins, this can take a long time..."
msgstr "Eklentileri geri yüklemek uzun zaman alabilir ..."

#: BackupManager.py:451
msgid "Rebooting..."
msgstr "Yeniden başlatılıyor ..."

#: BackupManager.py:459
msgid "Do you want to restore your enigma2 settings ?"
msgstr "Enigma2 ayarlarınızı geri yüklemek istiyor musunuz?"

#: BackupManager.py:490
msgid "Sorry, but the restore failed."
msgstr "Üzgünüm, ancak geri yükleme başarısız."

#: BackupManager.py:517 RestoreWizard.py:159 RestoreWizard.py:270
msgid "A background update check is in progress, please try again."
msgstr "Bir arka plan güncelleme kontrolü devam ediyor, lütfen tekrar deneyin."

#: BackupManager.py:554
#, python-format
msgid "Your %s %s is not connected to a network. Please check your network settings and try again."
msgstr "%s %s cihazınız bir ağa bağlı değil. Lütfen ağ ayarlarınızı kontrol edin ve tekrar deneyin."

#: BackupManager.py:563
msgid "Sorry the feeds are down for maintenance. Please try again later."
msgstr "Üzgünüz, özet akışları bakım için kapalı. Lütfen daha sonra tekrar deneyin."

#: BackupManager.py:572
#, python-format
msgid "Your %s %s is not connected to the Internet. Please check your network settings and try again."
msgstr "%s %s cihazınız İnternet'e bağlı değil. Lütfen ağ ayarlarınızı kontrol edin ve tekrar deneyin."

#: BackupManager.py:664
msgid "Do you want to restore your Enigma2 plugins ?"
msgstr "Enigma2 eklentilerinizi geri yüklemek istiyor musunuz?"

#: BackupManager.py:681
msgid "Now skipping restore process"
msgstr "Şimdi geri yükleme işlemi atlanıyor"

#: BackupManager.py:730
msgid "Select files/folders to backup"
msgstr "Yedeklenecek dosyaları / klasörleri seç"

#: BackupManager.py:744 BackupManager.py:844 BackupManager.py:943
#: MountManager.py:367 Multibootmgr.py:62 Multibootmgr.py:84
msgid "Cancel"
msgstr "İptal"

#: BackupManager.py:745 BackupManager.py:845 MountManager.py:366
msgid "Save"
msgstr "Kaydet"

#: BackupManager.py:778
msgid "Deselect"
msgstr "Seçimi kaldır"

#: BackupManager.py:780
msgid "Select"
msgstr "Seç"

#: BackupManager.py:831
msgid "Select extra packages folder"
msgstr "Ek paketler klasörü seç"

#: BackupManager.py:874
msgid "Select folder that contains plugins"
msgstr "Eklentiler içeren klasörü seç"

#: BackupManager.py:900
msgid "Please enter a folder that contains some packages."
msgstr "Lütfen bazı paketler içeren bir klasör girin."

#: BackupManager.py:944 RestoreWizard.py:111
msgid "OK"
msgstr "Tamam"

#: BackupManager.py:945
msgid "Choose files"
msgstr "Dosya seç"

#: BackupManager.py:946
msgid "Choose local IPK's folder"
msgstr "Yerel IPK'nın klasörünü seç"

#: BackupManager.py:969 SoftcamManager.py:545
msgid "Logs"
msgstr "Günlükler"

#: BackupManager.py:984
msgid "Backup created"
msgstr "Yedek oluşturuldu"

#: BackupManager.py:1086
#, python-format
msgid ""
"Your %s %s is about to run a backup of your settings and to detect your plugins.\n"
"Do you want to allow this?"
msgstr ""
"%s %s ayarlarınızda bir yedek çalıştırmak ve eklentilerinizi tespit etmek üzere.\n"
"Buna izin vermek istiyor musunuz?"

#: BackupManager.py:1111 ImageManager.py:651
msgid "Enough retries, delaying till next schedule."
msgstr "Bir sonraki programa kadar erteleme yeterlidir."

#: BackupManager.py:1149 BackupManager.py:1153
msgid "Starting..."
msgstr "Başlatılıyor ..."

#: BackupManager.py:1165 BackupManager.py:1169 BackupManager.py:1181
#: BackupManager.py:1185
msgid "Backing up files..."
msgstr "Dosyalar yedekleniyor ..."

#: BackupManager.py:1173 BackupManager.py:1177
msgid "Preparing extra plugins..."
msgstr "Fazladan eklentiler hazırlanıyor ..."

#: BackupManager.py:1189
msgid "Backup complete..."
msgstr "Yedekleme tamamlandı ..."

#: BackupManager.py:1250
msgid "The backup location does not have enough free space."
msgstr "Yedekleme yerinde yeterli boş alan yok."

#: BackupManager.py:1290
msgid "Plugin listing failed - e. g. wrong backup destination or no space left on backup device."
msgstr "Eklenti listesi başarısız oldu - örneğin yanlış yedekleme hedefi veya yedekleme cihazında boş alan kalmadı."

#: BackupManager.py:1358
msgid "Backup failed - e. g. wrong backup destination or no space left on backup device."
msgstr "Yedekleme başarısız - örn. yanlış yedekleme hedefi veya yedekleme cihazında boş alan kalmamış."

#: H9SDmanager.py:34
msgid "H9 SDcard manager"
msgstr "H9 SD kart yöneticisi"

#: H9SDmanager.py:56
msgid "Press appropiate Init to move Nand root to SDcard."
msgstr "Nand kökü SDcard'a taşımak için uygun Init tuşuna basın."

#: H9SDmanager.py:57
msgid "Reboot"
msgstr "Yeniden başlat"

#: H9SDmanager.py:58 Multibootmgr.py:65 Multibootmgr.py:89
msgid "Init SDcard"
msgstr "SDcard'ı başlat"

#: H9SDmanager.py:73
msgid "Init Zgemma H9 SDCARD - please reboot after use."
msgstr "Init Zgemma H9 SDCARD - lütfen kullanımdan sonra yeniden başlatın."

#: H9SDmanager.py:97
msgid "Init Zgemma H9 USB/SDA1 - please reboot after use."
msgstr "Init Zgemma H9 USB / SDA1 - lütfen kullanımdan sonra yeniden başlatın."

#: IPKInstaller.py:37 IPKInstaller.py:180
msgid "IPK installer"
msgstr "IPK yükleyici"

#: IPKInstaller.py:65 IPKInstaller.py:187 ImageManager.py:1361
#: SoftcamManager.py:118 SwapManager.py:128 ui.py:78
msgid "Close"
msgstr "Kapat"

#: IPKInstaller.py:66 IPKInstaller.py:188
msgid "Install"
msgstr "Yükle"

#: IPKInstaller.py:94 IPKInstaller.py:113
msgid "Extra IPK's"
msgstr "Ekstra IPK'lar"

#: IPKInstaller.py:97
msgid "It seems you have not setup an extra location. Please set it up in the Backup manager setup menu."
msgstr "Görünüşe göre fazladan bir konum ayarlamadınız. Lütfen bunu Backup manager kurulum menüsünde ayarlayın."

#: IPKInstaller.py:99 IPKInstaller.py:103
msgid "Change location"
msgstr "Konumu değiştir"

#: IPKInstaller.py:101
msgid "Sorry but that location does not exist or is not setup. Please set it up in the Backup manager setup menu."
msgstr "Maalesef bu konum mevcut değil veya ayarlanmadı. Lütfen bunu Backup manager ayarlar menüsünde ayarlayın."

#: IPKInstaller.py:107 IPKInstaller.py:115
msgid "Temp folder"
msgstr "Temp klasörü"

#: IPKInstaller.py:117
msgid "Select a package to install:"
msgstr "Kurulacak paketi seçin:"

#: IPKInstaller.py:135
msgid "Are you ready to install ?"
msgstr "Yüklemeye hazır mısınız?"

#: IPKInstaller.py:137
msgid "Install confirmation"
msgstr "Yükleme onayı"

#: IPKInstaller.py:145
msgid "Installing..."
msgstr "Yükleniyor ..."

#: IPKInstaller.py:148
msgid "Do you want to restart GUI now ?"
msgstr "GUI'yi şimdi yeniden başlatmak istiyor musunuz?"

#: IPKInstaller.py:150
msgid "Restart GUI."
msgstr "GUI'yi yeniden başlat."

#: IPKInstaller.py:190
msgid "Invert"
msgstr "Tersine çevir"

#: IPKInstaller.py:191
msgid "Press OK to toggle the selection."
msgstr "Seçimi değiştirmek için OK tuşuna basın."

#: ImageManager.py:111 ImageManager.py:183 ImageManager.py:341
#: ImageManager.py:362 ImageManager.py:767 ui.py:68
msgid "Image manager"
msgstr "Görüntü yöneticisi"

#: ImageManager.py:134
msgid "Flash"
msgstr "Flash"

#: ImageManager.py:136 ImageManager.py:1345
msgid "Downloads"
msgstr "İndirilenler"

#: ImageManager.py:238
msgid "Device: None available"
msgstr "Cihaz: Yok"

#: ImageManager.py:257 ImageManager.py:262
msgid "Select an image to flash:"
msgstr "Flaşlanacak bir resim seçin:"

#: ImageManager.py:262
msgid "Free space:"
msgstr "Boş alan:"

#: ImageManager.py:262 MountManager.py:133
msgid "MB"
msgstr "MB"

#: ImageManager.py:279
msgid "Do you want to change download url"
msgstr "İndirme URL'sini değiştirmek istiyor musunuz"

#: ImageManager.py:287
msgid "'User' url has not been specified, please use MENU button to initialise"
msgstr "'Kullanıcı' URL'si belirtilmedi, lütfen başlatmak için MENU düğmesini kullanın"

#: ImageManager.py:321
msgid ""
"Are you sure you want to delete this image backup:\n"
" "
msgstr ""
"Bu resim yedeklemesini silmek istediğinizden emin misiniz:\n"
" "

#: ImageManager.py:325
msgid "There is no image to delete."
msgstr "Silinecek resim yok."

#: ImageManager.py:350
msgid ""
"Do you want to create a full image backup?\n"
"This can take about 6 minutes to complete."
msgstr ""
"Tam bir görüntü yedeği oluşturmak istiyor musunuz?\n"
"Bu işlemin tamamlanması yaklaşık 6 dakika sürebilir."

#: ImageManager.py:352
msgid "Backup confirmation"
msgstr "Yedekleme onayı"

#: ImageManager.py:390
#, python-format
msgid ""
"Recording(s) are in progress or coming up in few seconds!\n"
"Do you still want to flash image\n"
"%s?"
msgstr ""
"Kayıtlar devam ediyor veya birkaç saniye içinde çıkıyor!\n"
"Hala görüntüyü flaş etmek istiyor musunuz\n"
"%s?"

#: ImageManager.py:392
#, python-format
msgid ""
"Do you want to flash image\n"
"%s"
msgstr ""
"Görüntüyü flaş etmek istiyor musunuz\n"
"%s"

#: ImageManager.py:394
msgid ""
"You are about to flash an eMMC flash; we cannot take any responsibility for any errors or damage to your box during this process.\n"
"Proceed with CAUTION!:\n"
"Are you sure you want to flash this image:\n"
" "
msgstr ""
"Bir eMMC flaşı yanıp sönmek üzeresiniz; bu işlem sırasında kutunuzdaki herhangi bir hata veya hasar için herhangi bir sorumluluk kabul edemeyiz.\n"
"DİKKAT ile devam edin!:\n"
"Bu resmi flaşlamak istediğinizden emin misiniz:\n"
" "

#: ImageManager.py:396
msgid ""
"Are you sure you want to flash this image:\n"
" "
msgstr ""
"Bu resmi flaşlamak istediğinizden emin misiniz:\n"
" "

#: ImageManager.py:398
msgid "Flash confirmation"
msgstr "Flaş onayı"

#: ImageManager.py:427
#, python-format
msgid "slot%s - %s"
msgstr "slot%s - %s"

#: ImageManager.py:427
#, python-format
msgid "slot%s - %s (current image)"
msgstr "slot%s - %s (geçerli resim)"

#: ImageManager.py:443
msgid "There is no image to flash."
msgstr "Flash görüntü yok."

#: ImageManager.py:445
msgid "You have decided not to flash image."
msgstr "Görüntüyü flaş etmemeye karar verdiniz."

#: ImageManager.py:450
#, python-format
msgid "Please wait while the flash prepares, after the image is flashed, your %s will restart - if error please use Recovery mode to restart."
msgstr "Lütfen flaş hazırlanırken bekleyin, görüntü yanıp söndükten sonra %s 'niz yeniden başlatılır - hata olursa lütfen yeniden başlatmak için Kurtarma modunu kullanın."

#: ImageManager.py:452
msgid "Please wait while the flash prepares."
msgstr "Lütfen flaş hazırlanırken bekleyin."

#: ImageManager.py:464
msgid "Flash image unzip successful."
msgstr "Flash resmi unzip başarılı."

#: ImageManager.py:466
msgid ""
"ET8500 Multiboot: Yes to restore OS1 No to restore OS2:\n"
" "
msgstr ""
"ET8500 Multiboot: OS1'i geri yüklemek için Evet OS2'yi geri yüklemek için Hayır:\n"
" "

#: ImageManager.py:468
msgid "ET8500 Image Restore"
msgstr "ET8500 Görüntü Geri Yükleme"

#: ImageManager.py:472 ImageManager.py:1248
msgid "Multiboot only able to restore this backup to mmc slot1"
msgstr "Çoklu önyükleme yalnızca bu yedeklemeyi mmc slot1'e geri yükleyebilir"

#: ImageManager.py:478
#, python-format
msgid ""
"Unzip error (also sent to any debug log):\n"
"%s"
msgstr ""
"Sıkıştırılmış hata (hata ayıklama günlüğüne de gönderilir):\n"
"%s"

#: ImageManager.py:525
#, python-format
msgid ""
"OFGwrite error (also sent to any debug log):\n"
"%s"
msgstr ""
"OFGwrite hatası (hata ayıklama günlüğüne de gönderilir):\n"
"%s"

#: ImageManager.py:534
msgid "Multiboot ERROR! - no STARTUP in boot partition."
msgstr "Çoklu önyükleme HATASI! - önyükleme bölümünde BAŞLATMA yok."

#: ImageManager.py:626
#, python-format
msgid ""
"Your %s %s is about to create a full image backup, this can take about 6 minutes to complete.\n"
"Do you want to allow this?"
msgstr ""
"%s %s tam bir görüntü yedeklemesi oluşturmak üzere, bu işlemin tamamlanması yaklaşık 6 dakika sürebilir.\n"
"Buna izin vermek istiyor musunuz?"

#: ImageManager.py:769
msgid "Setting up..."
msgstr "Ayarlanıyor ..."

#: ImageManager.py:773
msgid "Checking free RAM.."
msgstr "Ücretsiz RAM denetleniyor .."

#: ImageManager.py:777
msgid "Creating SWAP.."
msgstr "SWAP oluşturuluyor .."

#: ImageManager.py:781 ImageManager.py:785
msgid "Backing up kernel..."
msgstr "Çekirdek yedekleniyor ..."

#: ImageManager.py:789 ImageManager.py:793
msgid "Backing up root file system..."
msgstr "Kök dosya sistemi yedekleniyor ..."

#: ImageManager.py:797
msgid "Backing up eMMC partitions for USB flash ..."
msgstr "USB flash için eMMC bölümleri yedekleniyor ..."

#: ImageManager.py:801
msgid "Backing up eMMC partitions for USB flash..."
msgstr "USB flash için eMMC bölümleri yedekleniyor ..."

#: ImageManager.py:805 ImageManager.py:809
msgid "Removing temp mounts..."
msgstr "Geçici bağlantıların kaldırılması ..."

#: ImageManager.py:813 ImageManager.py:817
msgid "Moving to backup Location..."
msgstr "Yedeği yedeklemeye geçiliyor ..."

#: ImageManager.py:821 ImageManager.py:825
msgid "Creating zip..."
msgstr "Zip oluşturuluyor ..."

#: ImageManager.py:829
msgid "Backup complete."
msgstr "Yedekleme tamamlandı."

#: ImageManager.py:850
msgid "The backup location does not have enough free space.\n"
msgstr "Yedekleme yerinde yeterli boş alan yok.\n"

#: ImageManager.py:887
msgid "Sorry, not enough free RAM found, and no physical devices that supports SWAP attached. Can't create SWAP file on network or fat32 file-systems, unable to make backup."
msgstr "Üzgünüm, yeterli boş RAM bulunamadı ve SWAP'ı destekleyen fiziksel cihazlar bağlı değil. Ağda veya fat32 dosya sistemlerinde SWAP dosyası oluşturulamıyor, yedekleme yapılamıyor."

#: ImageManager.py:975 ImageManager.py:978 ImageManager.py:981
#: ImageManager.py:983 ImageManager.py:985
msgid "Create:"
msgstr "Oluştur:"

#: ImageManager.py:1360
#, python-format
msgid "Select an image to download for %s:"
msgstr "%s için indirmek için bir resim seçin:"

#: ImageManager.py:1362
msgid "Download"
msgstr "İndir"

#: ImageManager.py:1369
msgid "No images found for selected download server...if password check validity"
msgstr "Seçilen indirme sunucusu için resim bulunamadı ... eğer şifre kontrol geçerliliği"

#: ImageManager.py:1411
#, python-format
msgid "Image Version %s"
msgstr "Görüntü Sürümü%s"

#: ImageManager.py:1481
msgid "Compress"
msgstr "Sıkıştır"

#: ImageManager.py:1481
msgid "Expand"
msgstr "Genişlet"

#: ImageManager.py:1483
msgid "DownLoad"
msgstr "DownLoad"

#: ImageManager.py:1513
msgid ""
"Are you sure you want to download this image:\n"
" "
msgstr ""
"Bu resmi indirmek istediğinizden emin misiniz:\n"
" "

#: ImageManager.py:1515
msgid "Download confirmation"
msgstr "İndirme onayı"

#: ImageManager.py:1532
msgid "Downloading"
msgstr "İndiriliyor"

#: MountManager.py:84
msgid "HARD DISK: "
msgstr "SABİT DİSK: "

#: MountManager.py:96
msgid "USB: "
msgstr "USB: "

#: MountManager.py:102
msgid "SDCARD: "
msgstr "SDCARD: "

#: MountManager.py:109 MountManager.py:111 MountManager.py:122
msgid "None"
msgstr "Yok"

#: MountManager.py:110 MountManager.py:123 MountManager.py:135
msgid "unavailable"
msgstr "kullanılamıyor"

#: MountManager.py:123 MountManager.py:129 MountManager.py:131
#: MountManager.py:133 MountManager.py:135
msgid "Size: "
msgstr "Boyut: "

#: MountManager.py:129
msgid "TB"
msgstr "TB"

#: MountManager.py:131
msgid "GB"
msgstr "GB"

#: MountManager.py:144 MountManager.py:278 MountManager.py:293
msgid "Mount: "
msgstr "Bağla: "

#: MountManager.py:144
msgid "Type: "
msgstr "Tür: "

#: MountManager.py:195 ui.py:70
msgid "Mount manager"
msgstr "Mount yöneticisi"

#: MountManager.py:217
msgid "Setup mounts"
msgstr "Kurulum bağlar"

#: MountManager.py:218
msgid "Un-mount"
msgstr "Montajdan kaldır"

#: MountManager.py:219
msgid "Mount"
msgstr "Bağla"

#: MountManager.py:241
msgid "Use as HDD"
msgstr "HDD Olarak Kullan"

#: MountManager.py:257
msgid "Please wait while scanning for devices..."
msgstr "Lütfen cihazları tararken bekleyin ..."

#: MountManager.py:284
msgid "Mount failed."
msgstr "Bağlama başarısız."

#: MountManager.py:301
msgid "Can't un-mount the partition; make sure it is not being used for SWAP or record/timeshift paths."
msgstr "Bölüm kaldırılamıyor; SWAP veya kayıt / zaman kaydırma yolları için kullanılmadığından emin olun."

#: MountManager.py:318
msgid "This device is already mounted as HDD."
msgstr "Bu aygıt zaten HDD olarak monte edilmiş."

#: MountManager.py:353
msgid "Choose where to mount your devices to:"
msgstr "Cihazlarınızı nereye monte edeceğinizi seçin:"

#: MountManager.py:376
#, python-format
msgid "Please wait while scanning your %s %s devices..."
msgstr "%s %s cihazlarınızı tararken lütfen bekleyin ..."

#: MountManager.py:398
msgid "Updating mount locations..."
msgstr "Bağlama konumları güncelleniyor ..."

#: MountManager.py:400
msgid "Please wait."
msgstr "Lütfen bekleyin."

#: MountManager.py:403
#, python-format
msgid ""
"The changes need a system restart to take effect.\n"
"Restart your %s %s now?"
msgstr ""
"Değişikliklerin etkili olması için sistemin yeniden başlatılması gerekir.\n"
"%s %s cihazınızı şimdi yeniden başlatmak istiyor musunuz?"

#: MountManager.py:405
#, python-format
msgid "Restart %s %s."
msgstr "%s %s Yeniden başlatın."

#: Multibootmgr.py:39
msgid "Multiboot image manager"
msgstr "Çoklu önyükleme görüntü yöneticisi"

#: Multibootmgr.py:63
msgid "Press Init to format SDcard."
msgstr "SD kartı formatlamak için Init tuşuna basın."

#: Multibootmgr.py:85
msgid "Use the cursor keys to select an installed image and then Erase button."
msgstr "Yüklü bir görüntüyü seçmek için imleç tuşlarını kullanın ve ardından Sil düğmesini tıklayın."

#: Multibootmgr.py:86
msgid "Note: slot list does not show current image or empty slots."
msgstr "Not: yuva listesi geçerli görüntüyü veya boş yuvaları göstermiyor."

#: Multibootmgr.py:87
msgid "Erase"
msgstr "Sil"

#: Multibootmgr.py:92
msgid "Retrieving image slots - Please wait..."
msgstr "Görüntü yuvaları alınıyor - Lütfen bekleyin ..."

#: Multibootmgr.py:127
msgid "Empty slot"
msgstr "Boş yuva"

#: Multibootmgr.py:128
#, python-format
msgid "slot%s - %s "
msgstr "slot%s - %s "

#: Multibootmgr.py:136
#, python-format
msgid "Removal of this slot will not show in %s Gui.  Are you sure you want to delete image slot %s ?"
msgstr "Bu yuvanın kaldırılması %s Gui'de gösterilmez.  %s resim alanını silmek istediğinizden emin misiniz?"

#: Multibootmgr.py:140
#, python-format
msgid "Are you sure you want to delete image slot %s ?"
msgstr "% s resim yuvasını silmek istediğinizden emin misiniz?"

#: Multibootmgr.py:150
msgid "Init SDCARD"
msgstr "SDCARD'ı başlat"

#: Multibootmgr.py:152
msgid "Multiboot manager - Cannot initialise SDcard when running image on SDcard."
msgstr "Çoklu önyükleme yöneticisi - Görüntüyü SDcard üzerinde çalıştırırken SDcard başlatılamıyor."

#: Multibootmgr.py:155
#, python-format
msgid "Multiboot manager - to use this routine %s image must be at OpenViX 4.2.043 or later and USB flashed - reply Yes to continue"
msgstr "Çoklu önyükleme yöneticisi - Bu rutin %s görüntüyü kullanmak için OpenViX 4.2.043 veya sonrasında olmalı ve USB yanıp sönüyor - devam etmek için Evet yanıtını verin"

#: Multibootmgr.py:165
msgid "Multiboot manager - The SDcard must be at least 8MB."
msgstr "Çoklu önyükleme yöneticisi - SD kart en az 8 MB olmalıdır."

#: Multibootmgr.py:180
msgid "Multiboot manager - SDcard initialization run, please restart your Image."
msgstr "Çoklu önyükleme yöneticisi - SDcard başlatma çalıştırması, lütfen Resminizi yeniden başlatın."

#: RestoreWizard.py:93
msgid "Exit the restore wizard"
msgstr "Geri yükleme sihirbazından çık"

#: RestoreWizard.py:93
msgid "OK, to perform a restore"
msgstr "Tamam, geri yükleme gerçekleştirmek için"

#: RestoreWizard.py:97
msgid "NO, do not restore settings"
msgstr "HAYIR, ayarları geri yükleme"

#: RestoreWizard.py:97
msgid "YES, to restore settings"
msgstr "EVET, ayarları geri yüklemek için"

#: RestoreWizard.py:103 RestoreWizard.py:106
msgid "YES, to restore plugins"
msgstr "EVET, eklentileri geri yüklemek için"

#: RestoreWizard.py:104 RestoreWizard.py:107
msgid "NO, do not restore plugins"
msgstr "HAYIR, eklentileri geri yükleme"

#: RestoreWizard.py:131 RestoreWizard.py:136
msgid "Please wait while the system gathers information..."
msgstr "Lütfen sistem bilgi toplarken bekleyin ..."

#: RestoreWizard.py:132 RestoreWizard.py:137 RestoreWizard.py:144
#: RestoreWizard.py:150 RestoreWizard.py:156 RestoreWizard.py:160
#: RestoreWizard.py:186 RestoreWizard.py:190 RestoreWizard.py:199
#: RestoreWizard.py:255 RestoreWizard.py:259 RestoreWizard.py:263
#: RestoreWizard.py:267 RestoreWizard.py:271 plugin.py:181
msgid "Restore wizard"
msgstr "Geri yükleme sihirbazı"

#: RestoreWizard.py:143
msgid "Please wait while plugins restore completes..."
msgstr "Lütfen eklentilerin geri yüklenmesi tamamlanırken bekleyin ..."

#: RestoreWizard.py:149
msgid "Sorry the feeds are down for maintenance. Please try using Backup manager to restore plugins later."
msgstr "Üzgünüz, özet akışları bakım için kapalı. Lütfen eklentileri daha sonra geri yüklemek için Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:155
#, python-format
msgid "Your %s %s is not connected to the Internet. Please try using Backup manager to restore plugins later."
msgstr "%s %s cihazınız İnternet'e bağlı değil. Eklentileri daha sonra geri yüklemek için lütfen Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:198
msgid "Please wait while settings restore completes..."
msgstr "Lütfen ayarların geri yüklenmesi tamamlanırken bekleyin ..."

#: RestoreWizard.py:254
#, python-format
msgid "Your %s %s is not connected to a network. Please try using the Backup manager to restore plugins later when a network connection is available."
msgstr "%s % s cihazınız bir ağa bağlı değil. Lütfen bir ağ bağlantısı olduğunda eklentileri geri yüklemek için Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:258
#, python-format
msgid "Your %s %s could not connect to the plugin feeds at this time. Please try using the Backup manager to restore plugins later."
msgstr "%s %s, şu anda eklenti özet akışlarına bağlanamadı. Eklentileri daha sonra geri yüklemek için lütfen Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:262
#, python-format
msgid "Your %s %s is not connected to the Internet. Please try using the Backup manager to restore plugins later."
msgstr "%s %s cihazınız İnternet'e bağlı değil. Eklentileri daha sonra geri yüklemek için lütfen Yedekleme yöneticisini kullanmayı deneyin."

#: RestoreWizard.py:266
msgid "Sorry the feeds are down for maintenance. Please try using the Backup manager to restore plugins later."
msgstr "Üzgünüz, özet akışları bakım için kapalı. Lütfen eklentileri daha sonra geri yüklemek için Yedekleme yöneticisini kullanmayı deneyin."

#: ScriptRunner.py:43 plugin.py:175 ui.py:71
msgid "Script runner"
msgstr "Komut dosyası koşucusu"

#: ScriptRunner.py:65
msgid "Run"
msgstr "Çalıştır"

#: SoftcamManager.py:79 plugin.py:99 plugin.py:173
msgid "Softcam manager"
msgstr "Softcam yöneticisi"

#: SoftcamManager.py:80 ui.py:45
msgid "Main menu"
msgstr "Ana menü"

#: SoftcamManager.py:80 ui.py:45
msgid "Setup"
msgstr "Kurulum"

#: SoftcamManager.py:80
msgid "Softcam"
msgstr "Softcam"

#: SoftcamManager.py:95
msgid "Select:"
msgstr "Seç:"

#: SoftcamManager.py:96 SoftcamManager.py:169
msgid "Active:"
msgstr "Aktif:"

#: SoftcamManager.py:121 SwapManager.py:131
msgid "Autostart"
msgstr "Otomatik başlatma"

#: SoftcamManager.py:156
msgid "Start"
msgstr "Başlat"

#: SoftcamManager.py:158
msgid "Stop"
msgstr "Durdur"

#: SoftcamManager.py:162
msgid "Restart"
msgstr "Yeniden başlat"

#: SoftcamManager.py:165
msgid "Disable startup"
msgstr "Başlamayı devre dışı bırak"

#: SoftcamManager.py:167
msgid "Enable startup"
msgstr "Başlatmayı etkinleştir"

#: SoftcamManager.py:188
msgid ""
"Wait please while scanning\n"
"for softcam's..."
msgstr ""
"Tarama sırasında lütfen bekleyin\n"
"softcam için ..."

#: SoftcamManager.py:233 SoftcamManager.py:297
msgid ""
"No config files found, please setup CCcam first\n"
"in /etc/CCcam.cfg."
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce CCcam kurulumunu yapın\n"
"/etc/CCcam.cfg içinde."

#: SoftcamManager.py:238
msgid "CCcam can't run whilst MGcamd is running"
msgstr "MGcamd çalışırken CCcam çalışamıyor"

#: SoftcamManager.py:241
msgid ""
"No config files found, please setup Hypercam first\n"
"in /etc/hypercam.cfg."
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce Hypercam'ı kurun\n"
"/etc/hypercam.cfg içinde."

#: SoftcamManager.py:246
msgid ""
"No config files found, please setup Oscam first\n"
"in /etc/tuxbox/config"
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce Oscam'i kurun\n"
"/etc/tuxbox/config içinde"

#: SoftcamManager.py:252 SoftcamManager.py:308
msgid ""
"No config files found, please setup MGcamd first\n"
"in /usr/keys."
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce MGcamd kurulumunu yapın\n"
"içinde /usr/keys."

#: SoftcamManager.py:254 SoftcamManager.py:310
msgid "MGcamd can't run whilst CCcam is running."
msgstr "MGcamd CCcam çalışırken çalışamaz."

#: SoftcamManager.py:260 SoftcamManager.py:314
msgid "Found non-standard softcam, trying to start, this may fail."
msgstr "Standart dışı softcam bulundu, başlatmaya çalışıyor, bu başarısız olabilir."

#: SoftcamManager.py:295
msgid "CCcam can't run whilst MGcamd is running."
msgstr "MGcamd çalışırken CCcam çalışamıyor."

#: SoftcamManager.py:303
msgid ""
"No config files found, please setup Oscam first\n"
"in /etc/tuxbox/config."
msgstr ""
"Yapılandırma dosyası bulunamadı, lütfen önce Oscam'i kurun\n"
"/etc/tuxbox/config içinde."

#: SoftcamManager.py:332
msgid "Softcam starting..."
msgstr "Softcam başlıyor ..."

#: SoftcamManager.py:334
msgid "Please wait while starting\n"
msgstr "Lütfen başlarken bekleyin\n"

#: SoftcamManager.py:449
msgid "Softcam stopping..."
msgstr "Softcam duruyor ..."

#: SoftcamManager.py:451
msgid "Please wait while stopping\n"
msgstr "Lütfen dururken bekleyin\n"

#: SoftcamManager.py:633
msgid "SoftcamCheck"
msgstr "SoftcamKontrol"

#: SoftcamManager.py:635
msgid "Checking softcams..."
msgstr "Softcams kontrol ediliyor ..."

#: SwapManager.py:102 ui.py:72
msgid "SWAP manager"
msgstr "SWAP yöneticisi"

#: SwapManager.py:121
msgid "SWAP place:"
msgstr "SWAP yeri:"

#: SwapManager.py:123
msgid "SWAP size:"
msgstr "SWAP boyutu:"

#: SwapManager.py:125
msgid "Status:"
msgstr "Durum:"

#: SwapManager.py:126 SwapManager.py:253
msgid "Inactive"
msgstr "Aktif değil"

#: SwapManager.py:127 SwapManager.py:248
msgid "Active"
msgstr "Aktif"

#: SwapManager.py:129 SwapManager.py:252
msgid "Activate"
msgstr "Etkinleştir"

#: SwapManager.py:130 SwapManager.py:192
msgid "Create"
msgstr "Yarat"

#: SwapManager.py:154 SwapManager.py:248 SwapManager.py:253
msgid "Current status:"
msgstr "Şu anki durum:"

#: SwapManager.py:155
msgid "Wait please while scanning..."
msgstr "Lütfen tararken bekleyin ..."

#: SwapManager.py:247
msgid "Deactivate"
msgstr "Devre dışı bırak"

#: SwapManager.py:255
msgid "Enable SWAP at startup"
msgstr "Başlangıçta SWAP'yi etkinleştir"

#: SwapManager.py:271
msgid "SWAP file not found. You have to create the file before you try to activate it."
msgstr "SWAP dosyası bulunamadı. Etkinleştirmeye çalışmadan önce dosyayı oluşturmanız gerekir."

#: SwapManager.py:272 SwapManager.py:338
msgid "Info"
msgstr "Bilgi"

#: SwapManager.py:304
msgid "Please select device to use as SWAP file location."
msgstr "Lütfen SWAP dosyası konumu olarak kullanılacak cihazı seçin."

#: SwapManager.py:306
msgid "Sorry, no physical devices that supports SWAP attached. Can't create SWAP file on network or fat32 file-systems."
msgstr "Maalesef, SWAP'ı destekleyen hiçbir fiziksel cihaz bağlı değil. Ağda veya fat32 dosya sistemlerinde SWAP dosyası oluşturulamıyor."

#: SwapManager.py:311
msgid "128 Mb"
msgstr "128 Mb"

#: SwapManager.py:311
msgid "16 Mb"
msgstr "16 Mb"

#: SwapManager.py:311
msgid "256 Mb"
msgstr "256 Mb"

#: SwapManager.py:311
msgid "32 Mb"
msgstr "32 Mb"

#: SwapManager.py:311
msgid "64 Mb"
msgstr "64 Mb"

#: SwapManager.py:311
msgid "8 Mb"
msgstr "8 Mb"

#: SwapManager.py:311
msgid "96 Mb"
msgstr "96 Mb"

#: SwapManager.py:312
msgid "Select the SWAP file size:"
msgstr "SWAP dosya boyutunu seçin:"

#: SwapManager.py:317
msgid "Wait please while creating SWAP file..."
msgstr "SWAP dosyası oluşturulurken lütfen bekleyin ..."

#: SwapManager.py:337
msgid "You have to create a SWAP file before trying to activate the autostart."
msgstr "Otomatik başlatmayı etkinleştirmeye çalışmadan önce bir SWAP dosyası oluşturmanız gerekir."

#: plugin.py:84 plugin.py:170 ui.py:44
msgid "ViX"
msgstr "ViX"

#: plugin.py:164
msgid "Install extensions."
msgstr "Uzantıları yükle."

#: plugin.py:182
msgid "Ipkg"
msgstr "Ipkg"

#: plugin.py:183
msgid "ViX Backup manager"
msgstr "ViX Yedekleme yöneticisi"

#: plugin.py:184
msgid "ViX Image manager"
msgstr "ViX Görüntü yöneticisi"

#: plugin.py:185
msgid "ViX Mount manager"
msgstr "ViX Mount yöneticisi"

#: plugin.py:186
msgid "ViX Script runner"
msgstr "ViX Komut dosyası koşucusu"

#: plugin.py:187
msgid "ViX SWAP manager"
msgstr "ViX SWAP yöneticisi"

#: ui.py:67
msgid "Manage the backups of your settings."
msgstr "Ayarlarınızın yedeklerini yönetin."

#: ui.py:68
msgid "Create and flash complete images of your system."
msgstr "Sisteminizin eksiksiz görüntülerini oluşturun ve flash yapın."

#: ui.py:69
msgid "Install IPK's from your tmp folder."
msgstr "IPK'leri tmp klasörünüzden yükleyin."

#: ui.py:69
msgid "Install local extension"
msgstr "Yerel uzantıyı kur"

#: ui.py:70
msgid "Manage your devices mount points."
msgstr "Cihazlarınızın bağlama noktalarını yönetin."

#: ui.py:71
msgid "Run your shell scripts."
msgstr "Kabuk betiklerinizi çalıştırın."

#: ui.py:72
msgid "Create and Manage your SWAP files."
msgstr "SWAP dosyalarınızı oluşturun ve yönetin."

#: ui.py:74
msgid "Create empty slot."
msgstr "Boş yuva oluştur."

#: ui.py:74
msgid "MultiBoot manager"
msgstr "MultiBoot yöneticisi"

#: ui.py:76
msgid "H9SDcard Manager"
msgstr "H9SDcard Yöneticisi"

#: ui.py:76
msgid "Move Nand root to SD card"
msgstr "Nand kökünü SD karta taşı"
